module TestHLSHovercraft where

import Language.LSP.Types
import Relude
import Sisku.Hovercraft

testHLSHovercraft :: Text -> Hovercraft
testHLSHovercraft rootPath =
  Hovercraft
    { _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server",
      _pages =
        [ Page
            { _entries =
                [ Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = ""}), _range = Just (Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 33}})}, _definitions = [], _signatureToken = [], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "MyLib"}), _range = Just (Range {_start = Position {_line = 2, _character = 17}, _end = Position {_line = 2, _character = 22}})}, _definitions = [], _signatureToken = [], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nsomeFunc\n```\n\n*Defined in \8216MyLib\8217*\n *(test-haskell-language-server-0.1.0.0)*\n"}), _range = Just (Range {_start = Position {_line = 2, _character = 24}, _end = Position {_line = 2, _character = 32}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}, _range = Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 8}}}], _signatureToken = [[Ident {_identifier = "someFunc"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nmain\n```\n\n*Defined at " <> rootPath <> "/app/Main.hs:6:1*\n"}), _range = Just (Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 4}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}, _range = Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 4}}}], _signatureToken = [[Ident {_identifier = "main"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nIO\n```\n\n*Defined in \8216GHC.Types\8217*\n *(ghc-prim-0.7.0)*\n"}), _range = Just (Range {_start = Position {_line = 4, _character = 8}, _end = Position {_line = 4, _character = 10}})}, _definitions = [], _signatureToken = [[Ident {_identifier = "IO"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nmain :: IO ()\n```\n\n*Defined at " <> rootPath <> "/app/Main.hs:6:1*\n"}), _range = Just (Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 4}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}, _range = Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 4}}}], _signatureToken = [[Ident {_identifier = "main"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "IO"}, Symbol {_symbol = "("}, Symbol {_symbol = ")"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\n_ :: IO ()\n```\n"}), _range = Just (Range {_start = Position {_line = 5, _character = 7}, _end = Position {_line = 7, _character = 16}})}, _definitions = [], _signatureToken = [[Symbol {_symbol = "_"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "IO"}, Symbol {_symbol = "("}, Symbol {_symbol = ")"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nputStrLn :: String -> IO ()\n```\n\n*Defined in \8216System.IO\8217*\n *(base-4.15.1.0)*\n"}), _range = Just (Range {_start = Position {_line = 6, _character = 2}, _end = Position {_line = 6, _character = 10}})}, _definitions = [], _signatureToken = [[Ident {_identifier = "putStrLn"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "String"}, Symbol {_symbol = "-"}, Symbol {_symbol = ">"}, Ident {_identifier = "IO"}, Symbol {_symbol = "("}, Symbol {_symbol = ")"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\n_ :: String\n```\n"}), _range = Just (Range {_start = Position {_line = 6, _character = 11}, _end = Position {_line = 6, _character = 28}})}, _definitions = [], _signatureToken = [[Symbol {_symbol = "_"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "String"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/app/Main.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nsomeFunc :: IO ()\n```\n\n*Defined in \8216MyLib\8217*\n *(test-haskell-language-server-0.1.0.0)*\n"}), _range = Just (Range {_start = Position {_line = 7, _character = 2}, _end = Position {_line = 7, _character = 16}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}, _range = Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 8}}}], _signatureToken = [[Ident {_identifier = "someFunc"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "IO"}, Symbol {_symbol = "("}, Symbol {_symbol = ")"}]], _otherValues = [], _rootPath = toString rootPath}
                ]
            },
          Page
            { _entries =
                [ Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nsomeFunc\n```\n\n*Defined at " <> rootPath <> "/src/MyLib.hs:4:1*\n"}), _range = Just (Range {_start = Position {_line = 0, _character = 14}, _end = Position {_line = 0, _character = 22}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}, _range = Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 8}}}], _signatureToken = [[Ident {_identifier = "someFunc"}]], _otherValues = [], _rootPath = toString rootPath},
                  Entry {_document = TextDocumentIdentifier {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}}, _projectId = "com.github.takoeight0821.sisku.test-haskell-language-server", _hover = Hover {_contents = HoverContents (MarkupContent {_kind = MkMarkdown, _value = "\n```haskell\nsomeFunc :: IO ()\n```\n\n*Defined at " <> rootPath <> "/src/MyLib.hs:4:1*\n"}), _range = Just (Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 8}})}, _definitions = [Definition {_uri = Uri {getUri = "file://" <> rootPath <> "/src/MyLib.hs"}, _range = Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 8}}}], _signatureToken = [[Ident {_identifier = "someFunc"}, Symbol {_symbol = ":"}, Symbol {_symbol = ":"}, Ident {_identifier = "IO"}, Symbol {_symbol = "("}, Symbol {_symbol = ")"}]], _otherValues = [], _rootPath = toString rootPath}
                ]
            }
        ]
    }